# Generated by Django 6.0.1 on 2026-01-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologi',
            new_name='technology',
        ),
    ]
